SELECT 
    CASE 
    WHEN STUDENTS.MARKS < 70 
    THEN NULL
    ELSE STUDENTS.NAME
    END, 
    GRADES.GRADE, STUDENTS.MARKS 
FROM STUDENTS
INNER JOIN GRADES
ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK and GRADES.MAX_MARK
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME;