SELECT h.HACKER_ID, h.nAME FROM SUBMISSIONS s 
JOIN HACKERS h ON s.HACKER_ID = h.HACKER_ID
JOIN CHALLENGES c ON s.CHALLENGE_ID = c.CHALLENGE_ID
JOIN DIFFICULTY d ON c.DIFFICULTY_LEVEL = d.DIFFICULTY_LEVEL
WHERE s.SCORE = d.SCORE 
GROUP BY h.HACKER_ID, h.NAME
HAVING COUNT(*)>1 
ORDER BY COUNT(*) DESC, h.HACKER_ID;